name: 'TigerGraph in GitHub Actions'
description: 'Start a TigerGraph server (on default ports 9000 and 14240)'

branding:
  icon: 'database'
  color: 'orange'

inputs:
  tgserver-version:
    description: 'TigerGraph Server version to use (default "latest")'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tgserver-version }}